version: "3"
services:
    graph-node:
        image: jeffywu/graph-node:forking
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8020:8020"
            - "8030:8030"
            - "8040:8040"
        depends_on:
            - ipfs
            - postgres
        environment:
            postgres_host: postgres
            postgres_user: graph-node
            postgres_pass: let-me-in
            postgres_db: graph-node
            ipfs: "ipfs:5001"
            ethereum: "${SUBGRAPH_NETWORK}:${SUBGRAPH_NODE}"
            FORK_BASE: https://api.thegraph.com/subgraphs/id/
            DEBUG_FORK: QmQFAksNkZxyY6XdkEHAoWogYzouKRaq8pUCdVJoj6t2DL
            RUST_LOG: warn
            GRAPH_LOG: debug
    ipfs:
        image: ipfs/go-ipfs:v0.4.23
        ports:
            - "5001:5001"
    postgres:
        image: postgres:12
        ports:
            - "5432:5432"
        command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
        environment:
            POSTGRES_USER: graph-node
            POSTGRES_PASSWORD: let-me-in
            POSTGRES_DB: graph-node
